# Radarr - Movie management and automation
# Deploy: halvor install radarr
# Manual: docker compose up -d
#
# Requires: VPN service running (halvor install vpn)
# Access: http://localhost:7878

services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - HTTP_PROXY=http://pia-vpn:8888
      - HTTPS_PROXY=http://pia-vpn:8888
    volumes:
      - radarr_data:/config
      - ${MOVIES_PATH:-/mnt/media/movies}:/media/movies
      - ${DOWNLOADS_PATH:-/mnt/downloads}:/downloads
    ports:
      - 7878:7878
    networks:
      - vpn_network
    restart: unless-stopped

volumes:
  radarr_data:
    name: radarr_data

networks:
  vpn_network:
    external: true
