[package]
name = "halvor-db"
version = "0.1.0"
edition = "2021"

[dependencies]
halvor-core = { path = "../halvor-core" }
rusqlite.workspace = true
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
