apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traefik-public.fullname" . }}-secrets
  labels:
    {{- include "traefik-public.labels" . | nindent 4 }}
type: Opaque
data:
  cf-dns-api-token: {{ .Values.acme.dnsToken | b64enc }}

