apiVersion: v1
kind: Service
metadata:
  name: {{ include "traefik-public.fullname" . }}
  labels:
    {{- include "traefik-public.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.ports.http }}
    targetPort: web
    protocol: TCP
    name: http
  - port: {{ .Values.service.ports.https }}
    targetPort: websecure
    protocol: TCP
    name: https
  - port: {{ .Values.service.ports.dashboard }}
    targetPort: dashboard
    protocol: TCP
    name: dashboard
  selector:
    {{- include "traefik-public.selectorLabels" . | nindent 4 }}

