{{- if .Values.dashboard.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "traefik-private.fullname" . }}-dashboard
  labels:
    {{- include "traefik-private.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.dashboard.domain | default (printf "traefik.%s" .Values.domain) }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "traefik-private.fullname" . }}
            port:
              number: {{ .Values.service.ports.dashboard }}
{{- end }}

