{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "traefik-private.fullname" . }}
  labels:
    {{- include "traefik-private.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "traefik-private.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    {{- range .Values.networkPolicy.allowedIPs }}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
  - from:
    - namespaceSelector: {}
    - podSelector: {}
{{- end }}

