apiVersion: v1
kind: Service
metadata:
  name: {{ include "portainer.fullname" . }}
  labels:
    {{- include "portainer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if eq .Values.deploymentType "agent" }}
  - port: {{ .Values.service.ports.agent }}
    targetPort: agent
    protocol: TCP
    name: agent
  {{- else }}
  - port: {{ .Values.service.ports.web }}
    targetPort: web
    protocol: TCP
    name: web
  - port: {{ .Values.service.ports.ssl }}
    targetPort: ssl
    protocol: TCP
    name: ssl
  - port: {{ .Values.service.ports.edge }}
    targetPort: edge
    protocol: TCP
    name: edge
  {{- end }}
  selector:
    {{- include "portainer.selectorLabels" . | nindent 4 }}

