{{- if .Values.acme.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traefik.fullname" . }}-secrets
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
type: Opaque
stringData:
  cf-dns-api-token: {{ .Values.acme.dnsToken | quote }}
{{- end }}
