# Sonarr - TV show management and automation
# Deploy: halvor install sonarr
# Manual: docker compose up -d
#
# Requires: VPN service running (halvor install vpn)
# Access: http://localhost:8989

services:
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - HTTP_PROXY=http://pia-vpn:8888
      - HTTPS_PROXY=http://pia-vpn:8888
    volumes:
      - sonarr_data:/config
      - ${TV_PATH:-/mnt/media/tv}:/media/tv
      - ${DOWNLOADS_PATH:-/mnt/downloads}:/downloads
    ports:
      - 8989:8989
    networks:
      - vpn_network
    restart: unless-stopped

volumes:
  sonarr_data:
    name: sonarr_data

networks:
  vpn_network:
    external: true
