{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "halvor-server.fullname" . }}
  labels:
    {{- include "halvor-server.labels" . | nindent 4 }}
rules:
  {{- with .Values.serviceAccount.rules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}

