{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "halvor-server.fullname" . }}
  labels:
    {{- include "halvor-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "halvor-server.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default (include "halvor-server.fullname" .) }}
  namespace: {{ .Release.Namespace }}
{{- end }}

