apiVersion: v1
kind: Service
metadata:
  name: {{ include "halvor-server.fullname" . }}
  labels:
    {{- include "halvor-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.webPort }}
    targetPort: web
    protocol: TCP
    name: web
  - port: {{ .Values.service.agentPort }}
    targetPort: agent
    protocol: TCP
    name: agent
  selector:
    {{- include "halvor-server.selectorLabels" . | nindent 4 }}

