{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "pia-vpn.fullname" .) }}
  labels:
    {{- include "pia-vpn.labels" . | nindent 4 }}
{{- end }}

