apiVersion: v1
kind: Service
metadata:
  name: {{ include "pia-vpn.fullname" . }}
  labels:
    {{- include "pia-vpn.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: proxy
    protocol: TCP
    name: proxy
  - port: 1194
    targetPort: openvpn
    protocol: UDP
    name: openvpn
  selector:
    {{- include "pia-vpn.selectorLabels" . | nindent 4 }}

